### ISSUE TITLE
db.update does not update

### ISSUE THREAD

**Issue by tpasternak** [Softmotions/ejdb-node#11]
Such a program:

    var ejdb= require('ejdb')
    var db=ejdb.open('sampleDb');
    db.save('records', {firstName : "John", lastName : "Smith", age : 25});
    var updatedCount =
        db.update('records', {firstName : "John"}, {$set : {age : 26}});
    console.log(db.findOne('records'));
    console.log(updatedCount)

Gives the following output:

    { _id: '5506fec3d417583400000000',
      firstName: 'John',
      lastName: 'Smith',
      age: 25 }
    1

Shouldn't age be equal to 26 after update operation?

**Comment by tyutyunkov** [comment]
Hello!
Update commands should be included in query object, not in 'hints' object. 
Correct usage will be as follow:

```javascript
...
var updatedCount =
    db.update('records', {firstName : "John", $set : {age : 26}});
console.log(db.findOne('records'))
console.log(updatedCount)
```
Output:
```javascript
{ _id: '5507d74ea554ca5700000000',
  firstName: 'John',
  lastName: 'Smith',
  age: 26 }
1
```

**Comment by tpasternak** [comment]
Thanks, I'm sorry for the confusion.
