### ISSUE TITLE
npm install fails with node 0.11.9

### ISSUE THREAD

**Issue by r04r** [Softmotions/ejdb-node#2]
It seems to fail with a lot of v8 errors with [this](https://gist.github.com/r04r/40e4ed21452543675129) as the console output

**Comment by depeele** [comment]
It seems like this package requires node 0.10.*  It makes use of `child_process` `options.customFds` which was deprecated sometime around 0.11

I was able to successfully compile using node 0.10.36.


Are there any plans to update this to the newer versions of node (0.11 or 0.12)?

**Comment by tyutyunkov** [comment]
V8 used in node 0.12 has changes which are incompatible with current ejdb-node code.
We are working on migration to node 0.12. It may take some time.

**Comment by tyutyunkov** [comment]
Binding for node 0.12 is now available.
