### ISSUE TITLE
error installing on linux elementary : ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by cocodrino** [Softmotions/ejdb-node#3]
Hi...I'm receiving ths error...do you know what can I do?...thanks

sh: 1: node: not found
npm ERR! ejdb@1.1.25 preinstall: `node platform.js preinstall`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the ejdb@1.1.25 preinstall script.
npm ERR! This is most likely a problem with the ejdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node platform.js preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls ejdb
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-57-generic
npm ERR! command "nodejs" "/usr/local/bin/npm" "install" "-g" "ejdb"
npm ERR! cwd /home/yo
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.3.18
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/yo/npm-debug.log
npm ERR! not ok code 0

**Comment by adamansky** [comment]
This problem seems to be fixed.
