### ISSUE TITLE
Windows install fail

### ISSUE THREAD

**Issue by vird** [Softmotions/ejdb-node#7]
npm install adm-zip
ok
npm install ejdb
npm http GET https://registry.npmjs.org/ejdb
npm http 304 https://registry.npmjs.org/ejdb

> ejdb@1.1.25 preinstall E:\opt\node_sandbox\new_workspace\qgui2_crm\node_modules\ejdb
> node platform.js preinstall

Downloading windows binaries from: http://dl.dropboxusercontent.com/u/4709222/ejdb/tcejdb-1.1.25-min
gw32-i686.zip ...
File: ejdbdll\tcejdb-1.1.25-mingw32-i686.zip
Invalid response code 302
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by andyhu** [comment]
Any updates on this?

**Comment by andyhu** [comment]
I have successfully installed it by a workaround. Hope it can help others:
* Install http-server: `npm -g i http-server`
* Create an empty folder, and create same directory structure like in the url: `u\4709222\ejdb` and download the zip file in the error message and put it here
* Start a local web host `hs -p 80` at the newly created directory
* Modify `hosts` file to point dl.dropboxusercontent.com to 127.0.0.1
* `npm install ejdb`
Don't forget to restore the hosts file back after installation

**Comment by akaustel** [comment]
It seems Softmotions is back on the project, I hope they will provide a solution of this is still a problem. I did fix the whole thing with a much bigger workaround than your, but I already had sinopia (local npm server) running, so it was quite easy.

(Use @andyhu's solution unless you want to do it the hard way.)

* Cloned ejdb-node and initialized sub-repository 
* Fixed the install script to use my own server
* published parallel version of ejdb on private sinopia server
* `npm install ejdb`

**Comment by andyhu** [comment]
@akaustel I think there are simpler ways, since npm supports installing packages directly from github repo or via git.
Something like
```
npm -g i git://github.com/Softmotions/ejdb-node.git
```
will probably work (not tested)
